// ─── IRCTC Tatkal Agent — Train & Station Database ────────────────────────────
const IRCTC_DATA = {
  stations: [
    // ── Delhi / NCR ──────────────────────────────────────────────────────────
    { code: "NDLS", name: "New Delhi" },
    { code: "NZM",  name: "Hazrat Nizamuddin" },
    { code: "DLI",  name: "Delhi Junction" },
    { code: "DEE",  name: "Delhi Sarai Rohilla" },
    { code: "DSA",  name: "Delhi Shahdara" },
    { code: "GZB",  name: "Ghaziabad" },
    { code: "FDB",  name: "Faridabad" },
    { code: "GGN",  name: "Gurgaon" },
    { code: "SNP",  name: "Sonipat" },
    { code: "PNP",  name: "Panipat Junction" },
    // ── Mumbai ───────────────────────────────────────────────────────────────
    { code: "BCT",  name: "Mumbai Central" },
    { code: "CSTM", name: "Chhatrapati Shivaji Maharaj Terminus" },
    { code: "LTT",  name: "Lokmanya Tilak Terminus" },
    { code: "DR",   name: "Dadar" },
    { code: "TNA",  name: "Thane" },
    { code: "KYN",  name: "Kalyan Junction" },
    { code: "PNVL", name: "Panvel" },
    { code: "BSR",  name: "Vasai Road" },
    { code: "BVI",  name: "Borivali" },
    // ── Pune / Maharashtra ───────────────────────────────────────────────────
    { code: "PUNE", name: "Pune Junction" },
    { code: "KOP",  name: "Kolhapur" },
    { code: "SUR",  name: "Solapur Junction" },
    { code: "AWB",  name: "Aurangabad" },
    { code: "NED",  name: "Nanded" },
    { code: "NGP",  name: "Nagpur Junction" },
    { code: "AK",   name: "Akola Junction" },
    { code: "WR",   name: "Wardha Junction" },
    { code: "SEG",  name: "Shegaon" },
    { code: "BAD",  name: "Badnera Junction" },
    // ── Chennai / Tamil Nadu ─────────────────────────────────────────────────
    { code: "MAS",  name: "Chennai Central" },
    { code: "MS",   name: "Chennai Egmore" },
    { code: "MBM",  name: "Chennai Beach" },
    { code: "TPJ",  name: "Tiruchchirapalli Junction" },
    { code: "MDU",  name: "Madurai Junction" },
    { code: "TVC",  name: "Thiruvananthapuram Central" },
    { code: "NCJ",  name: "Nagercoil Junction" },
    { code: "CAPE", name: "Kanniyakumari" },
    { code: "CBE",  name: "Coimbatore Junction" },
    { code: "ED",   name: "Erode Junction" },
    { code: "SA",   name: "Salem Junction" },
    { code: "TJ",   name: "Thanjavur Junction" },
    { code: "JTJ",  name: "Jolarpettai Junction" },
    { code: "KPD",  name: "Katpadi Junction" },
    { code: "GDR",  name: "Gudur Junction" },
    { code: "TPTY", name: "Tirupati Junction" },
    { code: "RU",   name: "Renigunta Junction" },
    // ── Bengaluru / Karnataka ────────────────────────────────────────────────
    { code: "SBC",  name: "Bengaluru City" },
    { code: "YPR",  name: "Yesvantpur Junction" },
    { code: "BNC",  name: "Bengaluru Cantt" },
    { code: "MYS",  name: "Mysuru Junction" },
    { code: "MAQ",  name: "Mangaluru Junction" },
    { code: "MAJN", name: "Mangaluru Central" },
    { code: "UBL",  name: "Hubballi Junction" },
    { code: "GDG",  name: "Gadag Junction" },
    { code: "BJP",  name: "Vijayapura" },
    { code: "GTL",  name: "Guntakal Junction" },
    { code: "BLR",  name: "Ballari Junction" },
    // ── Hyderabad / Andhra Pradesh / Telangana ───────────────────────────────
    { code: "HYB",  name: "Hyderabad Deccan" },
    { code: "SC",   name: "Secunderabad Junction" },
    { code: "KCG",  name: "Kacheguda" },
    { code: "LPI",  name: "Lingampalli" },
    { code: "WL",   name: "Warangal" },
    { code: "KZJ",  name: "Kazipet Junction" },
    { code: "BZA",  name: "Vijayawada Junction" },
    { code: "GNT",  name: "Guntur Junction" },
    { code: "OGL",  name: "Ongole" },
    { code: "RJY",  name: "Rajahmundry" },
    { code: "VSKP", name: "Visakhapatnam Junction" },
    { code: "CLX",  name: "Chirala" },
    { code: "NDD",  name: "Nidadavolu Junction" },
    { code: "TUNI", name: "Tuni" },
    // ── Kerala ───────────────────────────────────────────────────────────────
    { code: "ERS",  name: "Ernakulam Junction" },
    { code: "ERN",  name: "Ernakulam Town" },
    { code: "ALLP", name: "Alappuzha" },
    { code: "QLN",  name: "Kollam Junction" },
    { code: "CLT",  name: "Kozhikode" },
    { code: "SRR",  name: "Shoranur Junction" },
    { code: "TCR",  name: "Thrissur" },
    { code: "PGT",  name: "Palakkad Junction" },
    // ── Kolkata / West Bengal ────────────────────────────────────────────────
    { code: "HWH",  name: "Howrah Junction" },
    { code: "SDAH", name: "Sealdah" },
    { code: "KGP",  name: "Kharagpur Junction" },
    { code: "ASN",  name: "Asansol Junction" },
    { code: "DHN",  name: "Dhanbad Junction" },
    { code: "MKA",  name: "Muri Junction" },
    { code: "BDC",  name: "Bandel Junction" },
    { code: "BWN",  name: "Barddhaman Junction" },
    { code: "NHT",  name: "New Cooch Behar" },
    { code: "NJP",  name: "New Jalpaiguri" },
    // ── Bihar / Jharkhand ────────────────────────────────────────────────────
    { code: "PNBE", name: "Patna Junction" },
    { code: "RJPB", name: "Rajendra Nagar Terminal" },
    { code: "GAYA", name: "Gaya Junction" },
    { code: "GYA",  name: "Gaya Junction" },
    { code: "JSME", name: "Jasidih Junction" },
    { code: "MFP",  name: "Muzaffarpur Junction" },
    { code: "SPJ",  name: "Samastipur Junction" },
    { code: "BJU",  name: "Barauni Junction" },
    { code: "CPH",  name: "Chapra Junction" },
    { code: "SEE",  name: "Sonpur Junction" },
    { code: "HJP",  name: "Hajipur Junction" },
    { code: "RNC",  name: "Ranchi Junction" },
    { code: "BKSC", name: "Bokaro Steel City" },
    { code: "GMO",  name: "Gomoh Junction" },
    { code: "HZB",  name: "Hazaribag Road" },
    // ── UP / Prayagraj / Lucknow ─────────────────────────────────────────────
    { code: "ALD",  name: "Prayagraj Junction" },
    { code: "PRYJ", name: "Prayagraj (Sangam)" },
    { code: "CNB",  name: "Kanpur Central" },
    { code: "LKO",  name: "Lucknow Charbagh" },
    { code: "LJN",  name: "Lucknow Junction" },
    { code: "BSB",  name: "Varanasi Junction" },
    { code: "MZP",  name: "Mirzapur" },
    { code: "MGS",  name: "Pt. Deen Dayal Upadhyaya Jn" },
    { code: "DDU",  name: "Pt. Deen Dayal Upadhyaya Junction" },
    { code: "AGC",  name: "Agra Cantt" },
    { code: "AF",   name: "Agra Fort" },
    { code: "MTJ",  name: "Mathura Junction" },
    { code: "SPN",  name: "Shahjahanpur" },
    { code: "BE",   name: "Bareilly Junction" },
    { code: "MB",   name: "Moradabad Junction" },
    { code: "GKP",  name: "Gorakhpur Junction" },
    { code: "FD",   name: "Faizabad Junction" },
    { code: "LMR",  name: "Lakhimpur" },
    { code: "STV",  name: "Sitapur City" },
    // ── MP / Rajasthan ───────────────────────────────────────────────────────
    { code: "BPL",  name: "Bhopal Junction" },
    { code: "HBJ",  name: "Bhopal Habibganj" },
    { code: "INDB", name: "Indore Junction" },
    { code: "UJN",  name: "Ujjain Junction" },
    { code: "RTM",  name: "Ratlam Junction" },
    { code: "JBP",  name: "Jabalpur Junction" },
    { code: "KTE",  name: "Katni Junction" },
    { code: "STA",  name: "Satna" },
    { code: "ET",   name: "Itarsi Junction" },
    { code: "BINA", name: "Bina Junction" },
    { code: "GWL",  name: "Gwalior Junction" },
    { code: "JHS",  name: "Jhansi Junction" },
    { code: "JP",   name: "Jaipur Junction" },
    { code: "AII",  name: "Ajmer Junction" },
    { code: "JU",   name: "Jodhpur Junction" },
    { code: "BKN",  name: "Bikaner Junction" },
    { code: "UDZ",  name: "Udaipur City" },
    { code: "ABR",  name: "Abu Road" },
    { code: "KOTA", name: "Kota Junction" },
    { code: "SWM",  name: "Sawai Madhopur" },
    { code: "BTE",  name: "Bharatpur Junction" },
    { code: "BDTS", name: "Bandra Terminus" },
    // ── Gujarat ──────────────────────────────────────────────────────────────
    { code: "ADI",  name: "Ahmedabad Junction" },
    { code: "ST",   name: "Surat" },
    { code: "BRC",  name: "Vadodara Junction" },
    { code: "BL",   name: "Anand Junction" },
    { code: "RJT",  name: "Rajkot Junction" },
    { code: "JND",  name: "Jamnagar" },
    { code: "OKHA", name: "Okha" },
    { code: "PBR",  name: "Porbandar" },
    { code: "VRL",  name: "Veraval" },
    { code: "VG",   name: "Valsad" },
    { code: "NVS",  name: "Navsari" },
    { code: "AMLI", name: "Ankleshwar Junction" },
    { code: "BH",   name: "Bharuch Junction" },
    // ── Punjab / Haryana / HP ────────────────────────────────────────────────
    { code: "ASR",  name: "Amritsar Junction" },
    { code: "LDH",  name: "Ludhiana Junction" },
    { code: "CDG",  name: "Chandigarh Junction" },
    { code: "UMB",  name: "Ambala Cantonment" },
    { code: "FZR",  name: "Firozpur Cantt" },
    { code: "RPJ",  name: "Rohtak Junction" },
    { code: "RK",   name: "Rewari" },
    { code: "KLK",  name: "Kalka" },
    { code: "SML",  name: "Shimla" },
    // ── J&K / Uttarakhand ────────────────────────────────────────────────────
    { code: "JAT",  name: "Jammu Tawi" },
    { code: "SVDK", name: "Shri Mata Vaishno Devi Katra" },
    { code: "HRI",  name: "Haridwar Junction" },
    { code: "DDN",  name: "Dehradun" },
    { code: "KGM",  name: "Kathgodam" },
    // ── Northeast / Odisha / Chhattisgarh ────────────────────────────────────
    { code: "GHY",  name: "Guwahati" },
    { code: "DBRG", name: "Dibrugarh Junction" },
    { code: "SCL",  name: "Silchar" },
    { code: "AGT",  name: "Agartala" },
    { code: "APDJ", name: "Alipurduar Junction" },
    { code: "NBQ",  name: "New Bongaigaon" },
    { code: "RGD",  name: "Rangiya Junction" },
    { code: "PURI", name: "Puri" },
    { code: "BBS",  name: "Bhubaneswar" },
    { code: "CTC",  name: "Cuttack Junction" },
    { code: "BAM",  name: "Berhampur" },
    { code: "VZM",  name: "Vizianagaram Junction" },
    { code: "R",    name: "Raipur Junction" },
    { code: "BSP",  name: "Bilaspur Junction" },
    { code: "SGRL", name: "Singrauli" },
  ],

  trains: [
    // ── Rajdhani Express ─────────────────────────────────────────────────────
    { no: "12951", name: "Mumbai Rajdhani",             from: "NDLS", to: "BCT",  classes: ["1A","2A","3A"] },
    { no: "12952", name: "Mumbai Rajdhani",             from: "BCT",  to: "NDLS", classes: ["1A","2A","3A"] },
    { no: "12953", name: "August Kranti Rajdhani",      from: "NDLS", to: "BCT",  classes: ["1A","2A","3A"] },
    { no: "12954", name: "August Kranti Rajdhani",      from: "BCT",  to: "NDLS", classes: ["1A","2A","3A"] },
    { no: "12301", name: "Howrah Rajdhani",             from: "NDLS", to: "HWH",  classes: ["1A","2A","3A"] },
    { no: "12302", name: "Howrah Rajdhani",             from: "HWH",  to: "NDLS", classes: ["1A","2A","3A"] },
    { no: "12305", name: "Howrah Rajdhani (via Patna)", from: "NDLS", to: "HWH",  classes: ["1A","2A","3A"] },
    { no: "12306", name: "Howrah Rajdhani (via Patna)", from: "HWH",  to: "NDLS", classes: ["1A","2A","3A"] },
    { no: "12309", name: "Rajendra Nagar Rajdhani",     from: "NDLS", to: "RJPB", classes: ["1A","2A","3A"] },
    { no: "12310", name: "Rajendra Nagar Rajdhani",     from: "RJPB", to: "NDLS", classes: ["1A","2A","3A"] },
    { no: "12431", name: "Thiruvananthapuram Rajdhani", from: "NZM",  to: "TVC",  classes: ["1A","2A","3A"] },
    { no: "12432", name: "Thiruvananthapuram Rajdhani", from: "TVC",  to: "NZM",  classes: ["1A","2A","3A"] },
    { no: "12433", name: "Chennai Rajdhani",            from: "NZM",  to: "MAS",  classes: ["1A","2A","3A"] },
    { no: "12434", name: "Chennai Rajdhani",            from: "MAS",  to: "NZM",  classes: ["1A","2A","3A"] },
    { no: "22691", name: "Bengaluru Rajdhani",          from: "NDLS", to: "SBC",  classes: ["1A","2A","3A"] },
    { no: "22692", name: "Bengaluru Rajdhani",          from: "SBC",  to: "NDLS", classes: ["1A","2A","3A"] },
    { no: "12437", name: "Secunderabad Rajdhani",       from: "NZM",  to: "SC",   classes: ["1A","2A","3A"] },
    { no: "12438", name: "Secunderabad Rajdhani",       from: "SC",   to: "NZM",  classes: ["1A","2A","3A"] },
    { no: "12453", name: "Ranchi Rajdhani",             from: "NDLS", to: "RNC",  classes: ["1A","2A","3A"] },
    { no: "12454", name: "Ranchi Rajdhani",             from: "RNC",  to: "NDLS", classes: ["1A","2A","3A"] },
    { no: "12957", name: "Ahmedabad Rajdhani",          from: "NDLS", to: "ADI",  classes: ["1A","2A","3A"] },
    { no: "12958", name: "Ahmedabad Rajdhani",          from: "ADI",  to: "NDLS", classes: ["1A","2A","3A"] },
    { no: "20503", name: "Arunachal AC Express",        from: "NDLS", to: "NAHARLAGUN", classes: ["1A","2A","3A"] },
    // ── Shatabdi Express ─────────────────────────────────────────────────────
    { no: "12001", name: "Bhopal Shatabdi",             from: "NDLS", to: "BPL",  classes: ["CC","EC"] },
    { no: "12002", name: "Bhopal Shatabdi",             from: "BPL",  to: "NDLS", classes: ["CC","EC"] },
    { no: "12003", name: "Amritsar Shatabdi",           from: "NDLS", to: "ASR",  classes: ["CC","EC"] },
    { no: "12004", name: "Amritsar Shatabdi",           from: "ASR",  to: "NDLS", classes: ["CC","EC"] },
    { no: "12009", name: "Mumbai Shatabdi",             from: "NDLS", to: "BCT",  classes: ["CC","EC"] },
    { no: "12010", name: "Mumbai Shatabdi",             from: "BCT",  to: "NDLS", classes: ["CC","EC"] },
    { no: "12011", name: "Kalka Shatabdi",              from: "NDLS", to: "CDG",  classes: ["CC","EC"] },
    { no: "12012", name: "Kalka Shatabdi",              from: "CDG",  to: "NDLS", classes: ["CC","EC"] },
    { no: "12025", name: "Pune Shatabdi",               from: "PUNE", to: "BCT",  classes: ["CC","EC"] },
    { no: "12026", name: "Pune Shatabdi",               from: "BCT",  to: "PUNE", classes: ["CC","EC"] },
    { no: "12035", name: "Kathgodam Shatabdi",          from: "NDLS", to: "KGM",  classes: ["CC","EC"] },
    { no: "12036", name: "Kathgodam Shatabdi",          from: "KGM",  to: "NDLS", classes: ["CC","EC"] },
    { no: "12049", name: "Gatimaan Express",            from: "NZM",  to: "AGC",  classes: ["CC","EC"] },
    { no: "12050", name: "Gatimaan Express",            from: "AGC",  to: "NZM",  classes: ["CC","EC"] },
    { no: "12017", name: "Dehradun Shatabdi",           from: "NDLS", to: "DDN",  classes: ["CC","EC"] },
    { no: "12018", name: "Dehradun Shatabdi",           from: "DDN",  to: "NDLS", classes: ["CC","EC"] },
    { no: "12019", name: "Howrah Shatabdi",             from: "HWH",  to: "NDLS", classes: ["CC","EC"] },
    { no: "12020", name: "Howrah Shatabdi",             from: "NDLS", to: "HWH",  classes: ["CC","EC"] },
    { no: "12027", name: "Chennai Shatabdi",            from: "MAS",  to: "SBC",  classes: ["CC","EC"] },
    { no: "12028", name: "Chennai Shatabdi",            from: "SBC",  to: "MAS",  classes: ["CC","EC"] },
    // ── Vande Bharat Express ─────────────────────────────────────────────────
    { no: "22435", name: "Vande Bharat (NDLS-VNS)",     from: "NDLS", to: "BSB",  classes: ["CC","EC"] },
    { no: "22436", name: "Vande Bharat (VNS-NDLS)",     from: "BSB",  to: "NDLS", classes: ["CC","EC"] },
    { no: "22439", name: "Vande Bharat (NDLS-ASR)",     from: "NDLS", to: "ASR",  classes: ["CC","EC"] },
    { no: "22440", name: "Vande Bharat (ASR-NDLS)",     from: "ASR",  to: "NDLS", classes: ["CC","EC"] },
    { no: "20901", name: "Vande Bharat (MAS-CBE)",      from: "MAS",  to: "CBE",  classes: ["CC","EC"] },
    { no: "20902", name: "Vande Bharat (CBE-MAS)",      from: "CBE",  to: "MAS",  classes: ["CC","EC"] },
    { no: "20905", name: "Vande Bharat (SBC-MAS)",      from: "SBC",  to: "MAS",  classes: ["CC","EC"] },
    { no: "20906", name: "Vande Bharat (MAS-SBC)",      from: "MAS",  to: "SBC",  classes: ["CC","EC"] },
    { no: "22417", name: "Vande Bharat (NDLS-KTR)",     from: "NDLS", to: "SVDK", classes: ["CC","EC"] },
    { no: "22418", name: "Vande Bharat (KTR-NDLS)",     from: "SVDK", to: "NDLS", classes: ["CC","EC"] },
    { no: "22549", name: "Vande Bharat (SC-VSP)",       from: "SC",   to: "VSKP", classes: ["CC","EC"] },
    { no: "22550", name: "Vande Bharat (VSP-SC)",       from: "VSKP", to: "SC",   classes: ["CC","EC"] },
    // ── Mail / Express ───────────────────────────────────────────────────────
    { no: "12560", name: "Shiv Ganga Express",          from: "NDLS", to: "BSB",  classes: ["1A","2A","3A","SL"] },
    { no: "12559", name: "Shiv Ganga Express",          from: "BSB",  to: "NDLS", classes: ["1A","2A","3A","SL"] },
    { no: "12382", name: "Poorva Express",              from: "HWH",  to: "NDLS", classes: ["1A","2A","3A","SL"] },
    { no: "12381", name: "Poorva Express",              from: "NDLS", to: "HWH",  classes: ["1A","2A","3A","SL"] },
    { no: "12393", name: "Sampoorna Kranti Express",    from: "RJPB", to: "NDLS", classes: ["2A","3A","SL"] },
    { no: "12394", name: "Sampoorna Kranti Express",    from: "NDLS", to: "RJPB", classes: ["2A","3A","SL"] },
    { no: "12565", name: "Bihar Sampark Kranti",        from: "NDLS", to: "DBG",  classes: ["2A","3A","SL"] },
    { no: "12566", name: "Bihar Sampark Kranti",        from: "DBG",  to: "NDLS", classes: ["2A","3A","SL"] },
    { no: "11057", name: "Amritsar Express",            from: "CSTM", to: "ASR",  classes: ["1A","2A","3A","SL"] },
    { no: "11058", name: "Amritsar Express",            from: "ASR",  to: "CSTM", classes: ["1A","2A","3A","SL"] },
    { no: "12357", name: "Durgiana Express",            from: "HWH",  to: "ASR",  classes: ["2A","3A","SL"] },
    { no: "12358", name: "Durgiana Express",            from: "ASR",  to: "HWH",  classes: ["2A","3A","SL"] },
    { no: "12801", name: "Purushottam Express",         from: "NDLS", to: "PURI", classes: ["1A","2A","3A","SL"] },
    { no: "12802", name: "Purushottam Express",         from: "PURI", to: "NDLS", classes: ["1A","2A","3A","SL"] },
    { no: "12875", name: "Neelachal Express",           from: "NDLS", to: "PURI", classes: ["2A","3A","SL"] },
    { no: "12876", name: "Neelachal Express",           from: "PURI", to: "NDLS", classes: ["2A","3A","SL"] },
    { no: "12721", name: "Dakshin Express",             from: "NZM",  to: "HYB",  classes: ["2A","3A","SL"] },
    { no: "12722", name: "Dakshin Express",             from: "HYB",  to: "NZM",  classes: ["2A","3A","SL"] },
    { no: "12649", name: "Karnataka Sampark Kranti",    from: "NDLS", to: "YPR",  classes: ["2A","3A","SL"] },
    { no: "12650", name: "Karnataka Sampark Kranti",    from: "YPR",  to: "NDLS", classes: ["2A","3A","SL"] },
    { no: "22687", name: "Mumbai–Mysuru Express",       from: "LTT",  to: "MYS",  classes: ["2A","3A","SL"] },
    { no: "22688", name: "Mumbai–Mysuru Express",       from: "MYS",  to: "LTT",  classes: ["2A","3A","SL"] },
    { no: "12229", name: "Lucknow Mail",                from: "NDLS", to: "LKO",  classes: ["1A","2A","3A","SL"] },
    { no: "12230", name: "Lucknow Mail",                from: "LKO",  to: "NDLS", classes: ["1A","2A","3A","SL"] },
    { no: "12533", name: "Pushpak Express",             from: "LKO",  to: "BCT",  classes: ["2A","3A","SL"] },
    { no: "12534", name: "Pushpak Express",             from: "BCT",  to: "LKO",  classes: ["2A","3A","SL"] },
    { no: "12137", name: "Punjab Mail",                 from: "CSTM", to: "FZR",  classes: ["1A","2A","3A","SL"] },
    { no: "12138", name: "Punjab Mail",                 from: "FZR",  to: "CSTM", classes: ["1A","2A","3A","SL"] },
    { no: "12611", name: "Chennai Mail",                from: "MAS",  to: "NZM",  classes: ["2A","3A","SL"] },
    { no: "12612", name: "Chennai Mail",                from: "NZM",  to: "MAS",  classes: ["2A","3A","SL"] },
    { no: "16031", name: "Andaman Express",             from: "MAS",  to: "DBRG", classes: ["2A","3A","SL"] },
    { no: "16032", name: "Andaman Express",             from: "DBRG", to: "MAS",  classes: ["2A","3A","SL"] },
    { no: "12505", name: "North East Express",          from: "NDLS", to: "DBRG", classes: ["1A","2A","3A","SL"] },
    { no: "12506", name: "North East Express",          from: "DBRG", to: "NDLS", classes: ["1A","2A","3A","SL"] },
    { no: "12909", name: "Garib Rath Express",          from: "BDTS", to: "NZM",  classes: ["3A"] },
    { no: "12910", name: "Garib Rath Express",          from: "NZM",  to: "BDTS", classes: ["3A"] },
    { no: "12721", name: "Dakshin Express",             from: "NZM",  to: "HYB",  classes: ["2A","3A","SL"] },
    { no: "12483", name: "Amritsar Express",            from: "KOTA", to: "ASR",  classes: ["2A","3A","SL"] },
    { no: "12484", name: "Amritsar Express",            from: "ASR",  to: "KOTA", classes: ["2A","3A","SL"] },
    { no: "12625", name: "Kerala Express",              from: "NDLS", to: "TVC",  classes: ["1A","2A","3A","SL"] },
    { no: "12626", name: "Kerala Express",              from: "TVC",  to: "NDLS", classes: ["1A","2A","3A","SL"] },
    { no: "12627", name: "Karnataka Express",           from: "NDLS", to: "SBC",  classes: ["1A","2A","3A","SL"] },
    { no: "12628", name: "Karnataka Express",           from: "SBC",  to: "NDLS", classes: ["1A","2A","3A","SL"] },
    { no: "12687", name: "Dehradun Express",            from: "MAS",  to: "DDN",  classes: ["2A","3A","SL"] },
    { no: "12688", name: "Dehradun Express",            from: "DDN",  to: "MAS",  classes: ["2A","3A","SL"] },
    { no: "11015", name: "Kushinagar Express",          from: "LTT",  to: "GKP",  classes: ["2A","3A","SL"] },
    { no: "11016", name: "Kushinagar Express",          from: "GKP",  to: "LTT",  classes: ["2A","3A","SL"] },
    { no: "12555", name: "Gorakhdham Express",          from: "NDLS", to: "GKP",  classes: ["2A","3A","SL"] },
    { no: "12556", name: "Gorakhdham Express",          from: "GKP",  to: "NDLS", classes: ["2A","3A","SL"] },
    { no: "12057", name: "Jan Shatabdi (UDZ-ADI)",     from: "UDZ",  to: "ADI",  classes: ["CC","2S"] },
    { no: "12058", name: "Jan Shatabdi (ADI-UDZ)",     from: "ADI",  to: "UDZ",  classes: ["CC","2S"] },
    { no: "12413", name: "Jammu Rajdhani",              from: "JAT",  to: "NDLS", classes: ["1A","2A","3A"] },
    { no: "12414", name: "Jammu Rajdhani",              from: "NDLS", to: "JAT",  classes: ["1A","2A","3A"] },
    { no: "12473", name: "Sarvodaya Express",           from: "NDLS", to: "JU",   classes: ["2A","3A","SL"] },
    { no: "12474", name: "Sarvodaya Express",           from: "JU",   to: "NDLS", classes: ["2A","3A","SL"] },
    { no: "12217", name: "Chandigarh Intercity",        from: "NDLS", to: "CDG",  classes: ["CC","2S"] },
    { no: "12218", name: "Chandigarh Intercity",        from: "CDG",  to: "NDLS", classes: ["CC","2S"] },
    { no: "12345", name: "Saraighat Express",           from: "HWH",  to: "GHY",  classes: ["1A","2A","3A","SL"] },
    { no: "12346", name: "Saraighat Express",           from: "GHY",  to: "HWH",  classes: ["1A","2A","3A","SL"] },
    { no: "12423", name: "Dibrugarh Rajdhani",          from: "NDLS", to: "DBRG", classes: ["1A","2A","3A"] },
    { no: "12424", name: "Dibrugarh Rajdhani",          from: "DBRG", to: "NDLS", classes: ["1A","2A","3A"] },
    { no: "12813", name: "Steel Express",               from: "HWH",  to: "TATA", classes: ["2A","3A","SL"] },
    { no: "12814", name: "Steel Express",               from: "TATA", to: "HWH",  classes: ["2A","3A","SL"] },
    { no: "12261", name: "Howrah Duronto",              from: "HWH",  to: "CSTM", classes: ["1A","2A","3A"] },
    { no: "12262", name: "Howrah Duronto",              from: "CSTM", to: "HWH",  classes: ["1A","2A","3A"] },
    { no: "12213", name: "Yesvantpur Duronto",          from: "YPR",  to: "NDLS", classes: ["1A","2A","3A"] },
    { no: "12214", name: "Yesvantpur Duronto",          from: "NDLS", to: "YPR",  classes: ["1A","2A","3A"] },
    { no: "22209", name: "Mumbai Duronto",              from: "NDLS", to: "BCT",  classes: ["1A","2A","3A"] },
    { no: "22210", name: "Mumbai Duronto",              from: "BCT",  to: "NDLS", classes: ["1A","2A","3A"] },
    { no: "12235", name: "Dibrugarh Express",           from: "NDLS", to: "DBRG", classes: ["2A","3A","SL"] },
    { no: "12236", name: "Dibrugarh Express",           from: "DBRG", to: "NDLS", classes: ["2A","3A","SL"] },
    { no: "15959", name: "Kamrup Express",              from: "HWH",  to: "DBRG", classes: ["2A","3A","SL"] },
    { no: "15960", name: "Kamrup Express",              from: "DBRG", to: "HWH",  classes: ["2A","3A","SL"] },
    { no: "18449", name: "Hirakhand Express",           from: "VSKP", to: "JAGDALPUR", classes: ["2A","3A","SL"] },
    { no: "18450", name: "Hirakhand Express",           from: "JAGDALPUR", to: "VSKP", classes: ["2A","3A","SL"] },
  ],
};

if (typeof self    !== "undefined") self.IRCTC_DATA    = IRCTC_DATA;
if (typeof window  !== "undefined") window.IRCTC_DATA  = IRCTC_DATA;
if (typeof module  !== "undefined") module.exports = IRCTC_DATA;
